<a href="https://colab.research.google.com/github/hihowareyou2008/ML-Projects/blob/main/Car_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics

In [2]:
car_data = pd.read_csv("/content/car_price_prediction_.csv")

In [3]:
car_data.head()

,Car ID,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

In [4]:
car_data.shape

(2500, 10)

In [5]:
car_data.isnull().sum()

Car ID          0
Brand           0
Year            0
Engine Size     0
Fuel Type       0
Transmission    0
Mileage         0
Condition       0
Price           0
Model           0
dtype: int64

In [6]:
car_data.describe()

           Car ID       Year  Engine Size        Mileage         Price
count  2500.00000  2500.0000  2500.000000    2500.000000   2500.000000
mean   1250.50000  2011.6268     3.465240  149749.844800  52638.022532
std     721.83216     6.9917     1.432053   87919.952034  27295.833455
min       1.00000  2000.0000     1.000000      15.000000   5011.270000
25%     625.75000  2005.0000     2.200000   71831.500000  28908.485000
50%    1250.50000  2012.0000     3.400000  149085.000000  53485.240000
75%    1875.25000  2018.0000     4.700000  225990.500000  75838.532500
max    2500.00000  2023.0000     6.000000  299967.000000  99982.590000

In [8]:
car_data['Fuel Type'].value_counts()

Fuel Type
Diesel      655
Petrol      630
Electric    614
Hybrid      601
Name: count, dtype: int64

In [10]:
car_data['Brand'].value_counts()

Brand
Toyota      374
Audi        368
BMW         358
Mercedes    353
Honda       352
Tesla       348
Ford        347
Name: count, dtype: int64

In [13]:
car_data['Mileage'].value_counts()

Mileage
78672     2
204222    2
262063    2
27584     2
204249    2
         ..
210192    1
288927    1
121701    1
271615    1
17198     1
Name: count, Length: 2490, dtype: int64

In [12]:
car_data['Transmission'].value_counts()

Transmission
Manual       1308
Automatic    1192
Name: count, dtype: int64

In [23]:
car_data.drop(columns='Car ID', axis=1)

,Brand,Year,Engine Size,Fuel Type,Transmission,Mileage,Condition,Price,Model
0,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang
...,...,...,...,...,...,...,...,...,...
2495,Audi,2020,2.4,Petrol,Automatic,22650,Like New,61384.10,Q5
2496,Audi,2001,5.7,Hybrid,Manual,77701,Like New,24710.35,A3
2497,Ford,2021,1.1,Hybrid,Manual,272827,Like New,29902.45,Fiesta
2498,Audi,2002,4.5,Diesel,Manual,229164,Like New,46085.67,Q5
2499,Toyota,2005,4.6,Diesel,Automatic,80978,Used,16594.14,RAV4

In [30]:
renamed_col = car_data.rename(columns={'Fuel Type':'fuel_type'}, inplace=True)

In [32]:
car_data.head()

,Car ID,Brand,Year,Engine Size,fuel_type,Transmission,Mileage,Condition,Price,Model
0,1,Tesla,2016,2.3,Petrol,Manual,114832,New,26613.92,Model X
1,2,BMW,2018,4.4,Electric,Manual,143190,Used,14679.61,5 Series
2,3,Audi,2013,4.5,Electric,Manual,181601,New,44402.61,A4
3,4,Tesla,2011,4.1,Diesel,Automatic,68682,New,86374.33,Model Y
4,5,Ford,2009,2.6,Diesel,Manual,223009,Like New,73577.10,Mustang

In [27]:
label_encode = LabelEncoder()

In [33]:
labels = label_encode.fit_transform(car_data.fuel_type)
labels_2 = label_encode.fit_transform(car_data.Mileage)
labels_3 = label_encode.fit_transform(car_data.Transmission)
labels_4 = label_encode.fit_transform(car_data.Brand)

In [35]:
car_data['fuel_type'] = labels
car_data['Mileage'] = labels_2
car_data['Transmission'] = labels_3
car_data['Brand'] = labels_4

In [36]:
car_data.head()

,Car ID,Brand,Year,Engine Size,fuel_type,Transmission,Mileage,Condition,Price,Model,Fuel Type
0,1,5,2016,2.3,3,1,959,New,26613.92,Model X,3
1,2,1,2018,4.4,1,1,1200,Used,14679.61,5 Series,1
2,3,0,2013,4.5,1,1,1513,New,44402.61,A4,1
3,4,5,2011,4.1,0,0,594,New,86374.33,Model Y,0
4,5,2,2009,2.6,0,1,1846,Like New,73577.10,Mustang,0

In [37]:
car_data.drop(columns='Car ID', axis=1)

,Brand,Year,Engine Size,fuel_type,Transmission,Mileage,Condition,Price,Model,Fuel Type
0,5,2016,2.3,3,1,959,New,26613.92,Model X,3
1,1,2018,4.4,1,1,1200,Used,14679.61,5 Series,1
2,0,2013,4.5,1,1,1513,New,44402.61,A4,1
3,5,2011,4.1,0,0,594,New,86374.33,Model Y,0
4,2,2009,2.6,0,1,1846,Like New,73577.10,Mustang,0
...,...,...,...,...,...,...,...,...,...,...
2495,0,2020,2.4,3,0,215,Like New,61384.10,Q5,3
2496,0,2001,5.7,2,1,662,Like New,24710.35,A3,2
2497,2,2021,1.1,2,1,2255,Like New,29902.45,Fiesta,2
2498,0,2002,4.5,0,1,1889,Like New,46085.67,Q5,0
2499,6,2005,4.6,0,0,686,Used,16594.14,RAV4,0

In [38]:
car_data['Mileage'].value_counts()

Mileage
668     2
1679    2
2150    2
248     2
1680    2
       ..
1739    1
2388    1
1022    1
2236    1
151     1
Name: count, Length: 2490, dtype: int64

In [39]:
car_data['Transmission'].value_counts()

Transmission
1    1308
0    1192
Name: count, dtype: int64

In [40]:
car_data['fuel_type'].value_counts()

fuel_type
0    655
3    630
1    614
2    601
Name: count, dtype: int64

In [41]:
X = car_data.drop(columns=['Price', 'Mileage', 'Brand'], axis=1)
Y = car_data['Price']
print(X)
print(Y)

      Car ID  Year  Engine Size  fuel_type  Transmission Condition     Model  \
0          1  2016          2.3          3             1       New   Model X
1          2  2018          4.4          1             1      Used  5 Series
2          3  2013          4.5          1             1       New        A4
3          4  2011          4.1          0             0       New   Model Y
4          5  2009          2.6          0             1  Like New   Mustang
...      ...   ...          ...        ...           ...       ...       ...
2495    2496  2020          2.4          3             0  Like New        Q5
2496    2497  2001          5.7          2             1  Like New        A3
2497    2498  2021          1.1          2             1  Like New    Fiesta
2498    2499  2002          4.5          0             1  Like New        Q5
2499    2500  2005          4.6          0             0      Used      RAV4

      Fuel Type
0             3
1             1
2             1
3             0
4             0
...         ...
2495          3
2496          2
2497          2
2498          0
2499          0

[2500 rows x 8 columns]
0       26613.92
1       14679.61
2       44402.61
3       86374.33
4       73577.10
          ...
2495    61384.10
2496    24710.35
2497    29902.45
2498    46085.67
2499    16594.14
Name: Price, Length: 2500, dtype: float64

In [42]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.4, random_state=2)

In [43]:
print(X.shape, X_train.shape, X_test.shape)

(2500, 8) (1500, 8) (1000, 8)

In [44]:
print(X_train)
print(Y_train)

      Car ID  Year  Engine Size  fuel_type  Transmission Condition     Model  \
1187    1188  2007          4.3          2             1  Like New        X3
732      733  2012          2.5          1             0  Like New       Fit
815      816  2010          2.1          3             1      Used      CR-V
66        67  2017          2.0          2             0      Used      CR-V
81        82  2013          3.3          2             1      Used      CR-V
...      ...   ...          ...        ...           ...       ...       ...
674      675  2013          4.8          3             0       New   Model X
2408    2409  2017          2.6          0             0       New   Model 3
1099    1100  2001          1.5          2             1  Like New   Mustang
2347    2348  2022          2.9          3             1       New     Focus
1608    1609  2023          1.2          2             1       New  5 Series

      Fuel Type
1187          2
732           1
815           3
66            2
81            2
...         ...
674           3
2408          0
1099          2
2347          3
1608          2

[1500 rows x 8 columns]
1187    17161.68
732     58944.68
815      6970.43
66      84946.15
81       6814.43
          ...
674     41224.51
2408    70585.87
1099    82854.17
2347    33470.72
1608    16797.81
Name: Price, Length: 1500, dtype: float64

In [45]:
model = LinearRegression()
model_2 = Lasso()

In [46]:
model.fit(X_train, Y_train)
model_2.fit(X_train, Y_train)

ValueError: could not convert string to float: 'Like New'

In [47]:
x_train_prediction = model.predict(X_train)
x2_train_prediction = model_2.predict(X_train)
x_test_prediction = model.predict(X_test)
x2_test_prediction = model_2.predict(X_test)

ValueError: could not convert string to float: 'Like New'

In [48]:
print(x_train_prediction)
print(x2_train_prediction)

NameError: name 'x_train_prediction' is not defined

In [ ]:
plt.scatter(Y_train, x_train_prediction)
plt.xlabel("Actual Price")
plt.ylabel("Predicted price")
plt.title("Actual Price Vs. Predicted Price")
plt.show()

In [ ]:
# r squared error
score_1 = metrics.r2_score(Y_train, x_train_prediction)
score_2 = metrics.r2_score(Y_test, x_test_prediction)
score_3 = metrics.r2_score(Y_train, x2_train_prediction)
score_4 = metrics.r2_score(Y_test, x2_test_prediction)

print(score_1)
print(score_2)
print(score_3)
print(score_4)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Once your Google Drive is mounted, you can access your files. For example, if you have a CSV file named `my_data.csv` in the root of your Drive, you can load it using pandas like this:

```python
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/my_data.csv')
print(df.head())
```

Remember to replace `my_data.csv` with the actual path and name of your file.